### ISSUE TITLE
[META] Ideas for notebooks

### ISSUE THREAD

**Issue by jeffvestal** [jeffvestal/elastic_jupyter_notebooks#1]
List of ideas for demo notebooks in no order

### NLP Focused
- [x] [Loading an embedding model into elastic from HuggingFace](https://github.com/jeffvestal/elastic_jupyter_notebooks/blob/main/load_embedding_model_from_hf_to_elastic.ipynb)
- [x] [Loading a NER model into elastic](https://github.com/jeffvestal/elastic_jupyter_notebooks/blob/main/load_ner_model_from_hf_to_elastic.ipynb)
- [ ] Inserting external vectors into an index
- [x] [Using a loaded model in elastic to generate and store vectors](https://github.com/jeffvestal/elastic_jupyter_notebooks/blob/main/generate_vectors_on_ingest_to_elastic.ipynb.ipynb)
- [ ] Querying vectors in elastic with kNN (including filtering and hybrid)
- [ ] Load sentiment analysis model 
- [ ] fine tune classification model
- [ ] image vector search - serializing images - storing vectors - search..
- [ ] question-answering model
- [ ] quantization 

### Classification / Regression Focused
- [ ] Training Classification model in eland

### Anomaly Detection
- [ ] forecasting with AD
